[package]
name = "seeker_home_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
seeker_state.workspace = true
seeker_resource.workspace = true
seeker_config.workspace = true
seeker_trait.workspace = true